language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - "pip install sqlalchemy"
#   add packages required by tests (mock and nose are on Travis VM by default)
  - "pip install simplejson"
script:
  - "nosetests"
